spring:
  profiles:
    active: dev
---
server:
  port: 8011
spring:
  application:
    name: PRODUCT-PROVIDER
  profiles: dev
  datasource:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/aigou
          username: root
          password: 920801
mybatis-plus:
    mapper-locations: classpath:cn/itsource/mapper/*Mapper.xml
    type-aliases-package: cn.itsource.domain,cn.itsource.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
---
server:
  port: 8012
spring:
  application:
    name: PRODUCT-PROVIDER-TEST
  profiles: test
  datasource:
            driver-class-name: com.mysql.jdbc.Driver
            url: jdbc:mysql://localhost:3306/aigou
            username: root
            password: 920801
mybatis-plus:
    mapper-locations: classpath:cn/itsource/mapper/*Mapper.xml
    type-aliases-package: cn.itsource.domain,cn.itsource.query
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true